Models/Artist.cs
using System;
using System.Collections.Generic;

namespace fatmamba.Models
{
    public class Artist    
    {
        public string ArtistId { get; set; }
        public string ArtistName { get; set; }
        public int Score { get; set; }
        public string BattleId { get; set; }
    }
}

Models/Battle.cs
using System;

namespace fatmamba.Models
{
    public class Battle
    {
        public string BattleId { get; set; }
        public string BattleName { get; set; }
        public string BattleStatus { get; set; }
        public TimeSpan TimeLeft { get; set; }
        public Artist ArtistOne { get; set; }
        public Artist ArtistTwo { get; set; }
    }
}

Models/Passcode.cs
using System;

namespace fatmamba.Models
{
    public class Passcode
    {
        public string Code { get; set; }
    }
}

Models/Vote.cs
using System;

namespace fatmamba.Models
{
    public class Vote
    {
        public string UserId { get; set; }
        public string ArtistId { get; set; }
        public Passcode Passcode { get; set; }
    }
}

Controllers/ArtistController.cs
using System;
using fatmamba.Common;
using Microsoft.AspNetCore.Mvc;
using fatmamba.Models;

namespace fatmamba.Controllers
{
    public class ArtistController : Controller
    {
        private readonly RedisHelper db = new RedisHelper();
        
        // GET api/Artist
        [HttpGet]
        public IActionResult Get()
        {
            var artists = db.GetArtistSet();

            return View(artists);
        }

        // GET api/Artist/{id}
        [HttpGet]
        public IActionResult Get(int id)
        {
            return View(db.GetArtist(id.ToString()));
        }

        [HttpPost]
        public IActionResult Post(Artist artist)
        {
            db.AddOrUpdateArtist(artist);
            return Ok();
        }
    }
}

Controllers/BattleController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using fatmamba.Models;
using fatmamba.Common;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace fatmamba.Controllers
{
    [Route("api/[controller]")]
    public class BattleController : Controller
    {
        // POST api/battle/getstatus
        [HttpPost("getstatus")]
        public IActionResult GetStatus()
        {
            string requestData = String.Empty;
            using(var reader = new StreamReader(Request.Body))
            {
                requestData = reader.ReadToEnd();
            }

            Passcode passcode = JsonConvert.DeserializeObject<Passcode>(requestData);

            if (passcode.Code != ConfigHelper.Passcode)
            {
                return Unauthorized();
            }

            //TODO: Get Data from Redis
            RedisHelper redis = new RedisHelper();
            string currentBattleId = redis.GetCurrentBattleId();
            Battle battle = redis.GetBattle(currentBattleId);
            battle.BattleStatus = redis.GetBattleStatus();
            battle.TimeLeft = redis.GetBattleTimer();
            battle.ArtistOne.Score = redis.GetArtistOneScore();
            battle.ArtistTwo.Score = redis.GetArtistTwoScore();

            if (battle.ArtistOne.Score > battle.ArtistTwo.Score)
                redis.AddOrUpdateBattleWInner(battle.BattleId, battle.ArtistOne.ArtistId);

            if (battle.ArtistOne.Score < battle.ArtistTwo.Score)
                redis.AddOrUpdateBattleWInner(battle.BattleId, battle.ArtistTwo.ArtistId);

            return Json(battle);
        }

        // POST api/battle/vote
        [HttpPost("vote")]
        public IActionResult Vote()
        {
            // Read data from request
            string requestData = String.Empty;
            using(var reader = new StreamReader(Request.Body))
            {
                requestData = reader.ReadToEnd();
            }

            // Request data has to be formed to match Vote
            Vote vote = JsonConvert.DeserializeObject<Vote>(requestData);

            // Simple Passcode check...
            if (vote.Passcode.Code != ConfigHelper.Passcode)
            {
                return Unauthorized(); //401
            }

            var db = new RedisHelper();
            int userVoteWeight;
            var battleId = db.GetCurrentBattleId();

            //Add User if not exist w/ vote count
            if (db.GetUserBattleId(vote.UserId + "BattleId") != battleId)
            {
                userVoteWeight = 100;
                db.AddOrUpdateUser(vote.UserId, userVoteWeight);

                // This allows us to reset the vote weight per battle
                db.AddOrUpdateUserBattleId(vote.UserId + "BattleId", battleId);
            }
            else
            {
                userVoteWeight = db.GetUserVoteWeight(vote.UserId);
            }

            var battle = db.GetBattle(battleId);
            var artist = (vote.ArtistId == battle.ArtistOne.ArtistId) ? "artistOne" : "artistTwo";

            if (userVoteWeight != 1)
            {
                //Add Vote
                db.AddVoteForArtist(artist, userVoteWeight);

                //Decrement user vote, stops at 1
                userVoteWeight--;
                db.AddOrUpdateUser(vote.UserId, userVoteWeight);

                //TODO: Error decrement or vote
            }
            else 
            {
                //Add Vote of 1
                db.AddVoteForArtist(artist, userVoteWeight);
            }

            //Vote Was Successful
            return Ok(); //200
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using fatmamba.Models;

namespace fatmamba.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            var isDbConnected = new fatmamba.Common.RedisHelper().GetDatabase();
            ViewData["Message"] = "Your database status is: " + isDbConnected;

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using fatmamba.Common;
using fatmamba.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace fatmamba.Controllers
{
    public class TestController : Controller
    {
        // GET: /<controller>/
        public IActionResult Fun()
        {
            Artist art = new Artist
            {
                ArtistName = "Ian Philpot"
            };

            return View(art);
        }

        // GET: /<controller>/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Fun(Artist artist)
        {
            if (ModelState.IsValid)
            {
                var msg = artist.Score;
                return RedirectToAction("Success", new { message = msg });
            }

            return View(artist);
        }

        public IActionResult Success(string message)
        {
            ViewData["Message"] = "The score is: " + message;

            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "Ian Was Here";
}

<div class="ui container">
    <h2>@ViewData["Title"].</h2>
    <h3>@ViewData["Message"]</h3>

    <p>Use this area to provide additional information.</p> 
</div>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<div class="ui container">
    <h2>@ViewData["Title"]</h2>
    <h3>@ViewData["Message"]</h3>
    <address>
        One Microsoft Way<br/>
        Redmond, WA 98052-6399<br/>
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="ui blue inverted vertical masthead center aligned segment">

    <div class="ui text container">

        <h1 class="ui inverted header">
            MVC + Semantic UI
        </h1>
        <h2>If you build it, they will come.</h2>
        <a class="ui huge secondary button" href="http://semantic-ui.com/">
            Get Started <i class="right arrow icon"></i>
        </a>
    </div>

</div>
<div class="ui grid">
    <div class="eight wide column">
        <div class="ui segment">
            <h1 class="ui black ribbon label">How To</h1>
            <ol class="ui list">
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=699314">Add an appsetting in config and access it in app.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
            </ol>
        </div>
    </div>
    <div class="eight wide column">
        <div class="ui segment">
            <h1 class="ui black ribbon label">Overview</h1>
            <ol class="ui list">
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET 5</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET 5 such as Startup and middleware.</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
            </ol>
        </div>
    </div>

</div>
<div class="ui grid">

    <div class="eight wide column">
        <div class="ui segment">
            <h1 class="ui black ribbon label">Run & Deploy</h1>
            <ol class="ui list">
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=517852">Run your app on .NET Core</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run commands in your project.json</a></li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
            </ol>
        </div>
    </div>
    <div class="eight wide column">
        <div class="ui segment">
            <h1 class="ui black ribbon label">Application Uses</h1>
            <ol class="left aligned ui list">
                <li>Sample pages using ASP.NET MVC 6</li>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=518007">Gulp</a> and <a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
                <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
            </ol>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>@ViewData["Title"] - fatmamba</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/semantic/dist/semantic.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://oss.maxcdn.com/semantic-ui/2.1.8/semantic.min.css"
              asp-fallback-href="~/lib/semantic/dist/semantic.min.css"
              asp-fallback-test-class="ui button" asp-fallback-test-property="cursor" asp-fallback-test-value="pointer" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <!-- Following Menu -->
    <div class="ui large top pointing fixed menu">
        <div class="ui container">
            <a class="toc item">
                <i class="sidebar icon"></i>
                <span class="sr-only">Toggle Navigation</span>
            </a>
            <a href="/" class="header item">fatmamba</a>
            <menulink class="blue item" asp-area="" controller-name="Home" action-name="Index" menu-text="Home"></menulink>
            <menulink class="blue item" asp-area="" controller-name="Home" action-name="About" menu-text="About"></menulink>
            <menulink class="blue item" asp-area="" controller-name="Home" action-name="Contact" menu-text="Contact">Contact</menulink>

        </div>
    </div>

    <!-- Sidebar Menu -->
    <div class="ui vertical inverted sidebar menu">
        <menulink class="blue item" asp-area="" controller-name="Home" action-name="Index" menu-text="Home"></menulink>
        <menulink class="blue item" asp-area="" controller-name="Home" action-name="About" menu-text="About"></menulink>
        <menulink class="blue item" asp-area="" controller-name="Home" action-name="Contact" menu-text="Contact"></menulink>

    </div>

    <!-- Page Contents -->
    <div class="pusher">
        <div class="ui container content">
            @RenderBody()
        </div>

        <div class="ui vertical footer segment">
            <div class="ui container">
                <div class="ui stackable  divided equal height stackable grid">
                    <div class="three wide column">
                        <h4 class="ui header">About</h4>
                        <div class="ui  link list">
                            <a href="#" class="item">Sitemap</a>
                            <a href="#" class="item">Contact Us</a>
                            <a href="#" class="item">Link</a>
                            <a href="#" class="item">Link</a>
                        </div>
                    </div>
                    <div class="three wide column">
                        <h4 class="ui header">Services</h4>
                        <div class="ui  link list">
                            <a href="#" class="item">Service One</a>
                            <a href="#" class="item">Service Two</a>
                            <a href="#" class="item">Service Three</a>
                            <a href="#" class="item">Service Four</a>
                        </div>
                    </div>
                    <div class="ten wide column">
                        <h4 class="ui header">Footer Header</h4>
                        <p>Yes I know you probably disregarded the earlier boasts as non-sequitor filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/semantic/dist/semantic.js"></script>
        <script src="~/js/site.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.3.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://oss.maxcdn.com/semantic-ui/2.1.8/semantic.min.js"
                asp-fallback-src="~/lib/semantic/dist/semantic.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Views/Test/Fun.cshtml
@using fatmamba.Common
@model Artist

<div class="row">
    <h3 title="@Model.ArtistName">Hello @Model.ArtistName!</h3>
</div>

<form asp-controller="Test" asp-action="Fun" method="post">
    Score: <input asp-for="Score" /><br />
    @*<select asp-for="Country" asp-items="Model.Countries"></select>*@
    <br /><button type="submit">Register</button>
</form>

Views/Test/Success.cshtml
<h1>Success</h1>
<h3>@ViewData["Message"]</h3>